//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korona
{
    using System;
    using System.Collections.Generic;
    
    public partial class Betegek
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public Nullable<int> Eletkor { get; set; }
        public string Elerhetoseg { get; set; }
        public string Neme { get; set; }
        public Nullable<int> Taj_szam { get; set; }
    }
}
