//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korona
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_table
    {
        public int Id { get; set; }
        public string Beteg_neve { get; set; }
        public Nullable<bool> Alapbetegseg { get; set; }
        public string Death_date { get; set; }
    }
}
